sudo: required
services:
  - docker
script:
  - docker build -t vinob/test-ci-cd .
  - docker images vinob/test-ci-cd
before_deploy:
  - docker login -u vinob -p dhvin123
deploy:
  provider: script
  script: docker push vinob/test-ci-cd
  on:
    branch: master